### PR TITLE
Implementation to obtain the canonical, selfie, inchi and inchi key representation of a smile using the Datamol library

### PR DESCRIPTION
**Pull request by carcablop**
Implementing Datamol preprocessing to obtain the canonical, selfie, inchi and inchi key form of a smile. 
Docker configured with python version 3.8

### CODE REVIEW

**Comment by carcablop** [comment]
Hi @GemmaTuron .
Initially I had an error related to "Tags" telling me that the tags were not available in Ersilia. I solved it by leaving the ones that were already there (in the airtable), that means that I can't modify the tag or add more than the ones that are initially added at the time of opening the PR of the model, if I don't open a PR in the tag.txt to suggest more? . And should I exclusively use the ones indicated in the documentation?. Thanks Gemma. Just to clarify.

**Comment by GemmaTuron** [comment]
Hi @carcablop !

The tags have been structured by us to restrict them, otherwise there are too many different tags and they become unusable for quick searches. The [documentation](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/contribute-models/model-incorporation-guidelines) contains the list of accepted tags, you should choose from there. 
For this model I would suggest: `Chemical notation`
In addition, please keep in mind that all the fields are pre-coded, and things like "under the Apache-2 ..." will also result in an error. If the license is an Apache-2, as you can see in the documentation the right format would be: "Apache-2.0"

**Comment by GemmaTuron** [comment]
@miquelduranfrigola Can we analyse this PR? Why the latest edit has not triggered the model_test_PR ? I only see two successful checks
@carcablop I don't see the latest test on the PR, so i am unsure if it is passing it or not

**Comment by carcablop** [comment]
> @miquelduranfrigola¿Podemos analizar este PR? ¿Por qué la última edición no ha activado model_test_PR? Solo veo dos comprobaciones exitosas @carcablopNo veo la última prueba en PR, así que no estoy seguro de si la está pasando o no.

@GemmaTuron I made the change on my local, committed and then pushed to my repository. And the changes were reflected here in this pull request, when I updated I saw that the tests had passed.

**Comment by carcablop** [comment]
> Hola @carcablop !
> 
> Hemos estructurado las etiquetas para restringirlas, de lo contrario, hay demasiadas etiquetas diferentes y se vuelven inutilizables para búsquedas rápidas. La [ documentación ](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/contribute-models/model-incorporation-guidelines) contiene la lista de etiquetas aceptadas, debe elegir desde allí. Para este modelo te sugiero: `Chemical notation`Además, tenga en cuenta que todos los campos están precodificados, y cosas como "bajo Apache-2..." también generarán un error. Si la licencia es una Apache-2, como puedes ver en la documentación el formato correcto sería: "Apache-2.0"

No license related error was generated, so the test should have failed because of the license too. I have updated the tag and the license.

**Comment by GemmaTuron** [comment]
mmm I see the model_test_pr was triggered in your previous commits, but not in the latest, where I only have two checks:

@github-actions
json syntax check / json-test (pull_request) Successful in 23s

@gitguardian
GitGuardian Security Checks Successful in 32s — No secrets detected ✅

but let's merge and see what happens!

**Pull request merged**
